### ISSUE TITLE
Invoke-SCuBAConfigAppUI does not exist

### ISSUE THREAD

**Issue by jbclarkman** [cisagov/ScubaGear#1814]
### Prerequisites

- [x] This issue has an informative and human-readable title.

### ScubaGear Version

Attempting to execute command: Invoke-SCuBAConfigAppUI returns that the module does not exist or belong to the cmdlet

### Operating System

Windows 11

### PowerShell Version

5.1

### M365 Environment and License(s)

GCC High

### 🐛 Summary

The documentation references the use of Invoke-SCuBAConfigAppUI but that command does not exist even after invoking scuba and importing the scubagear module and updating to the latest version. 

### Steps to reproduce

1. Launch Scuba
2. Run Invoke-SCuBAConfigAppUI

### Expected behavior

Opens the Scuba YAML Configuration GUI

**Comment by mitchelbaker-cisa** [comment]
@jbclarkman Thanks for the report. We are rolling out the SCuBA config UI in two phases, the first being documentation updates and then the second the required code updates. As you've pointed out we've merged the documentation changes into the main branch, but the code updates are still in review. Please hang tight until v1.7.0 which is when we plan on officially releasing the SCUBA config UI. 

I also recommend viewing the ScubaGear repository using the v1.6.0 tag, https://github.com/cisagov/ScubaGear/tree/v1.6.0. This will show the state of the project corresponding to v1.6.0 if that's the version you're running.

**Comment by DickTracyII** [comment]
Just for awareness. The new command will be `Start-SCuBAConfigApp` when released.

**Comment by DickTracyII** [comment]
@jbclarkman While the official latest module is not release yet; however, the main branch repo now has the included UI. If you don't mind, please test it out and send feedback.

**Comment by DomingoLaMosa** [comment]
@DickTracyII Still not working. I downloaded the ScubaGear module a moment ago and installed all the dependencies. When I ran the command "Start-ScubaConfigApp" after importing the SubaGear module, verifying that I have the latest version, permissions, it tells me:
"Start-ScubaConfigApp: The term 'Start-ScubaConfigApp' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

**Comment by DickTracyII** [comment]
If you have the ScubaGear module (version 1.6.0) from PowerShell gallery  installed on your device and you downloaded a copy of this repo to your devices, when you import the downloaded version, you must use `-Force`. This will overwrite what is loaded in the `PSModulePath`. 

Example
```powershell
Import-Module C:\Users\DomingoLaMosa\Downloads\ScubaGear-Main\PowerShell\ScubaGear\ScubaGear.psd1 -Force
Get-Command -module ScubaGear
```

<img width="1308" height="584" alt="Image" src="https://github.com/user-attachments/assets/0528a29c-544a-4d60-8b09-109a4593d84e" />

**Comment by DickTracyII** [comment]
#update

I just saw that the prerelease candidate is published to PowerShell Gallery. you can install that if you like. I would uninstall the old one so there is no conflict

`Find-Module scubagear -AllowPrerelease | Install-Module -Scope CurrentUser`

<img width="1729" height="751" alt="Image" src="https://github.com/user-attachments/assets/30ccefca-c2c8-49b9-b2de-bedc1f9f33e6" />

**Comment by DickTracyII** [comment]
@jbclarkman can I close this issue? did you see the release candidate?
